import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'theme/app_theme.dart';
import 'screens/home_screen.dart';
import 'services/history_service.dart';
import 'services/ai_service.dart';
import 'services/settings_service.dart';
import 'services/monetization_controller.dart';
import 'services/auth_service.dart';
// import 'firebase_options.dart'; // Removing as file doesn't exist

import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await dotenv.load(fileName: ".env");
    // Initialize Firebase - Assuming default options or platform specific
    // If firebase_options.dart is generated by FlutterFire CLI, use it.
    // Otherwise, we might need to rely on google-services.json/GoogleService-Info.plist being picked up automatically.
    // For now, I'll try with DefaultFirebaseOptions if available, else just init.
    // Since I can't see generated files easily, I will try to perform a safe init.
    // EDIT: User scenario implies just "firebase_core" added.
    // I will use a try-catch block for Firebase init to be safe if options aren't perfect yet.
    try {
      // Fallback or explicit init if added later
      await Firebase.initializeApp();
    } catch (e) {
      // Fallback if DefaultFirebaseOptions is not generated yet or we are on a platform that auto-detects
      debugPrint("Firebase init failed, checking manual config: $e");
      try {
        // In some cases, we might want to manually init if platform-specific auto-init failed
        // But for now, we just rely on platform files.
      } catch (e2) {
        debugPrint("Double fail on firebase init: $e2");
      }
    }

    await MobileAds.instance.initialize();
  } catch (e) {
    debugPrint("Initialization failed: $e");
    // Continue anyway so the app doesn't hang on a black screen
  }

  runApp(const ReplyRizzApp());
}

class ReplyRizzApp extends StatelessWidget {
  const ReplyRizzApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => HistoryService()..loadHistory()),
        ChangeNotifierProvider(
          create: (_) => SettingsService()..loadSettings(),
        ),
        ChangeNotifierProvider(create: (_) => MonetizationController()),
        ChangeNotifierProvider(create: (_) => AuthService()),
        Provider(create: (_) => AIService()),
      ],
      child: Consumer<SettingsService>(
        builder: (context, settings, _) {
          return MaterialApp(
            title: 'ReplyRizz',
            debugShowCheckedModeBanner: false,
            theme: AppTheme
                .lightTheme, // You need to define lightTheme in AppTheme
            darkTheme: AppTheme.darkTheme,
            themeMode: ThemeMode.dark, // Enforce Dark Mode
            home: const HomeScreen(),
          );
        },
      ),
    );
  }
}
